name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11, 12]
        dependency-version: [prefer-stable]

    steps:
      # Check out the repository code
      - name: Checkout
        uses: actions/checkout@v6

      # Set up the desired PHP version with extensions and coverage
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip, sodium
          coverage: pcov

      # Determine the Composer cache directory
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      # Cache both the Composer cache directory and the vendor directory
      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.COMPOSER_CACHE_DIR }}
            vendor
          key: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-deps-${{ hashFiles('composer.json', 'composer.lock') }}
          restore-keys: |
            php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-deps-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --with="laravel/framework:^${{ matrix.laravel }}"

      - name: Run Rector (Dry Run)
        run: composer test:refactor

      - name: Run Lint Tests
        run: composer test:lint

      - name: Run PHPStan
        run: composer test:types

      - name: Run Pest Tests
        run: composer test:unit
